[tool.poetry]
name = "dbt-aovivo"
version = "0.1.0"
description = ""
authors = ["fernando"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dbt-postgres = "^1.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
